# Generated by Django 5.2.16 on 2026-09-15 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('SETUP', 'Setup'), ('LIVE', 'Live'), ('ROUND_COMPLETE', 'Round complete'), ('COMPLETED', 'Completed')], db_index=True, default='SETUP', max_length=24)),
                ('active_category', models.CharField(db_index=True, default='A', max_length=32)),
                ('current_round', models.PositiveIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='draft_draft_status_a96ecf_idx'), models.Index(fields=['active_category'], name='draft_draft_active__8cbc5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DraftRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], db_index=True, default='UPCOMING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='draft.draft')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('photo', models.URLField(blank=True)),
                ('category', models.CharField(db_index=True, max_length=32)),
                ('playing_role', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='draft_playe_is_acti_8c6405_idx'), models.Index(fields=['category', 'name'], name='draft_playe_categor_141b28_idx')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('short', models.CharField(blank=True, max_length=12)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team-logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DraftTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], db_index=True, default='UPCOMING', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_turns', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='draft.draftround')),
                ('selected_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='draft.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_turns', to='draft.team')),
            ],
        ),
        migrations.CreateModel(
            name='DraftTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_teams', to='draft.draft')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_entries', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_entries', to='draft.team')),
            ],
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('pick_number', models.PositiveIntegerField()),
                ('client_action_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='draft.draft')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='draft.draftround')),
                ('turn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pick', to='draft.draftturn')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='draft.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='draft.team')),
            ],
            options={
                'ordering': ['pick_number'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager')], db_index=True, default='MANAGER', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='draftround',
            index=models.Index(fields=['draft', 'status'], name='draft_draft_draft_i_35475a_idx'),
        ),
        migrations.AddIndex(
            model_name='draftround',
            index=models.Index(fields=['draft', 'round_number'], name='draft_draft_draft_i_dea47f_idx'),
        ),
        migrations.AddConstraint(
            model_name='draftround',
            constraint=models.UniqueConstraint(fields=('draft', 'round_number'), name='unique_round_number_per_draft'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['manager'], name='draft_team_manager_96bd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='draftturn',
            index=models.Index(fields=['round', 'status'], name='draft_draft_round_i_801632_idx'),
        ),
        migrations.AddIndex(
            model_name='draftturn',
            index=models.Index(fields=['round', 'position'], name='draft_draft_round_i_8a7ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='draftturn',
            index=models.Index(fields=['manager', 'status'], name='draft_draft_manager_bfd773_idx'),
        ),
        migrations.AddConstraint(
            model_name='draftturn',
            constraint=models.UniqueConstraint(fields=('round', 'position'), name='unique_turn_position_per_round'),
        ),
        migrations.AddConstraint(
            model_name='draftturn',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('round',), name='one_active_turn_per_round'),
        ),
        migrations.AddConstraint(
            model_name='draftturn',
            constraint=models.UniqueConstraint(condition=models.Q(('selected_player__isnull', False)), fields=('round', 'selected_player'), name='one_selected_player_per_round_turns'),
        ),
        migrations.AddIndex(
            model_name='draftteam',
            index=models.Index(fields=['draft', 'team'], name='draft_draft_draft_i_55ca23_idx'),
        ),
        migrations.AddIndex(
            model_name='draftteam',
            index=models.Index(fields=['draft', 'manager'], name='draft_draft_draft_i_b48314_idx'),
        ),
        migrations.AddConstraint(
            model_name='draftteam',
            constraint=models.UniqueConstraint(fields=('draft', 'team'), name='unique_team_per_draft'),
        ),
        migrations.AddConstraint(
            model_name='draftteam',
            constraint=models.UniqueConstraint(fields=('draft', 'manager'), name='unique_manager_per_draft'),
        ),
        migrations.AddIndex(
            model_name='draftpick',
            index=models.Index(fields=['draft', 'team'], name='draft_draft_draft_i_3e5e03_idx'),
        ),
        migrations.AddIndex(
            model_name='draftpick',
            index=models.Index(fields=['draft', 'player'], name='draft_draft_draft_i_2e6e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='draftpick',
            index=models.Index(fields=['draft', 'client_action_id'], name='draft_draft_draft_i_2d2390_idx'),
        ),
        migrations.AddIndex(
            model_name='draftpick',
            index=models.Index(fields=['team', 'created_at'], name='draft_draft_team_id_613b28_idx'),
        ),
        migrations.AddConstraint(
            model_name='draftpick',
            constraint=models.UniqueConstraint(fields=('draft', 'player'), name='unique_player_pick_per_draft'),
        ),
        migrations.AddConstraint(
            model_name='draftpick',
            constraint=models.UniqueConstraint(fields=('draft', 'pick_number'), name='unique_pick_number_per_draft'),
        ),
        migrations.AddConstraint(
            model_name='draftpick',
            constraint=models.UniqueConstraint(fields=('draft', 'client_action_id'), name='unique_client_action_per_draft'),
        ),
    ]
