# Generated by Django 5.2.16 on 2026-09-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_project_alter_userprofile_role_category_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_category_name_per_project'),
        ),
    ]
